services:
  recruta-app:
    image: recruta-app:latest
    environment:
      - NODE_ENV=production
      # Passamos a URL explicitamente aqui para garantir que o container receba
      - DATABASE_URL=postgresql://postgres:devpcdigital@postgres:5432/recruta_artheria?schema=public
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
      - easypanel
    deploy:
      mode: replicated
      replicas: 1
      labels:
        # Configuração para o Traefik (EasyPanel) gerar o SSL
        - "traefik.enable=true"
        - "traefik.http.routers.recruta-artheria.rule=Host(`cxsquad.com.br`)"
        - "traefik.http.routers.recruta-artheria.entrypoints=websecure"
        - "traefik.http.routers.recruta-artheria.tls.certresolver=letsencrypt"
        - "traefik.http.services.recruta-artheria.loadbalancer.server.port=3000"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devpcdigital
      POSTGRES_DB: recruta_artheria
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      mode: replicated
      replicas: 1

networks:
  app-network:
    driver: overlay
  easypanel:
    external: true